### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by rodfersou** [collective/collective.taxonomy#87]
Need a end user documentation showing how to:

* Use the package
* Generate the taxonomy behavior
* Put some data
* And use it

(the cypress test will generate a movie in the end with all the steps, we can link it in the README)

**Comment by petschki** [comment]
just mentioning (not for this improvement step but for the future) that we use collective.taxonomy in combination with collective.collectionfilter, so that you get filtering for content categorized with taxonomies with minimal effort ... this might be worth a documentation chapter here and in collective.collectionfilter ...

productive example: https://www.weitererzaehlen.at/interviews (german only)
